.TH "wl_object" 3 "Tue Feb 21 2017" "Version 1.13.0" "Wayland" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wl_object \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wayland-server\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const struct \fBwl_interface\fP * \fBinterface\fP"
.br
.ti -1c
.RI "const void * \fBimplementation\fP"
.br
.ti -1c
.RI "uint32_t \fBid\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint32_t wl_object::id"

.SS "const void* wl_object::implementation"

.SS "const struct \fBwl_interface\fP* wl_object::interface"


.SH "Author"
.PP 
Generated automatically by Doxygen for Wayland from the source code\&.
